#
# ICOS Telemetruum Gateway
# Copyright © 2022 - 2025 Engineering Ingegneria Informatica S.p.A.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# This work has received funding from the European Union's HORIZON research
# and innovation programme under grant agreement No. 101070177.
#


telemetruumHubEndpoint: ""
telemetruumGRPCHubEndpoint: ""

agentId:

otel-collector:
  enabled: true
  image:
    repository: harbor.res.eng.it/icos/meta-kernel/observability/telemetruum/otel-collector-icos-distribution
    tag: 1.4.0-v0.115.0
    command:
    - /otelcol-icos
    - --config=/conf/otel-config.yaml
  service:
    ports:
      otlp:
        containerPort: 4317
      http:
        containerPort: 4318

extraCertsBundle:
  configmapName: ""
  configmapKey: ""